apiVersion: v1
kind: Service
metadata:
  name: caching-service
  namespace: staging
spec:
  selector:
    app: caching-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
